spring:
  application:
    name: "requests"
  datasource:
    url: jdbc:mysql://localhost:3307/requestsdb
    username: root
    password: root
  sql:
    init:
      mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect

server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    register-with-eureka: true
    fetch-registry: true
  instance:
    preferIpAddress: true

logging:
  level:
    com:
      connect:
        request: DEBUG